# Generated by Django 3.0.4 on 2020-03-05 07:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groceries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('qty', models.CharField(max_length=200)),
                ('receive_date', models.CharField(max_length=100)),
                ('expiration', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField(default=0)),
                ('sale_price', models.IntegerField(blank=True, default=0)),
                ('pro_type', models.CharField(max_length=200)),
                ('is_published', models.BooleanField(default=True)),
                ('date_publish', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
